---
title: "Homework Three"
author: "Alison Hall"
date: "1/29/2020"
output: html_document
---

# 1. 
To complete this problem we have to erase the tabs and add commas to where there used to be spaces. First, I used `\s` to select the spaces, and `{2}` to say I was only interesting in finding locations where there were two spaces. After selecting these areas with spaces, then I replaced them with a comma. If we didn't know that there were exactly two spaces, we could have added a comma after the 2 like this: `{2,}`. 
```

FIND: \s{2}
REPLACE:,

```


# 2. 
To complete this problem we can use  `\w` to isolate any words. Using a + sign with w means that we isolate any strings of letters longer than 1. That brought us to the comma and the space which were not placed in parentheses because we do not care to save them for the final version. Another new tool used here is the `.*` which is an includisve term that allows us to include anything left over.   

```
FIND: (\w+),\s(\w+),\s(.*)
REPLACE: \2 \1 (\3)
```


# 3.
To add a line break after a specific portion of the text we can isolate that piece of text (.mp3) and for good housekeeping make sure you catch the space following it to avoid having that space end up at the beginning of each line as well. Use `\n`to begin a new line after each occurance of .mp3.

```
FIND: (.mp3)\s
REPLACE: .mp3\n

```

# 4. 
Here we are combining several ideas. We use our ability to isolate pieces of the text we would like to save using parenthesis and specify what that text should contain using several regular expressions already reviewed. Then we use numbers proceeded by a `\` to specify the order we would like the saved segments to appear in, adding an _ where we want it. 

```
FIND: (\d{2,})\s+(.*)(.mp3)
REPLACE: \2_\1\3
```


# 5. 
For this challenge we isolated the aspects of interest which in this case is only the first letter of the first word, the second word in full of variable length, and the last digits. Not in parenthesis is all the junk we don't want to take along. We rearrange using the technique previously described.
```
FIND:(\w{1})\w+,(\w+),\d+.\d,(\d+)

REPLACE:\1_\2,\3
```


# 6. 
This puzzle asked us only to keep the first letter and discard the rest of the word the length of which is variable `(\w)\w*`. We also would like the keep only the first four letters of the next word, discarding the rest `(\w{4})\w*`. Finally there are numbers and a period we don't care about `\d*.\d`. We do want to keep what comes after that which is a comma a space and one more number `(.*)`. Arrange according to order number of the pieces in parenthesis and  add punctuation where needed. 
```
FIND:(\w)\w*,(\w{4})\w*,\d*.\d(.*)
REPLACE \1_\2\3
```

# 7. 
For this finall challenge, we rearrange the first 3 letters of two words selected by `(\w{3})` and ignore the ends of both of those words by follow up with this expression `\w+`. We choose to keep both sets of numbers isolating them by `(\d+.\d)` and `(\d)`. The those saved parts are organized and correct punctuation and spacing is added. 

```
FIND: (\w{3})\w+,(\w{3})\w+,(\d+.\d),(\d+)
REPLACE:\1\2, \4, \3


```
